### ISSUE TITLE
Feature Request - App Name/Bundle Id in Devices tab

### ISSUE THREAD

**Issue by sgruby** [kean/PulsePro#15]
In my devices tab, I have a bunch of simulators and devices. I can't tell which app is which. I'd love to be able to see more of an identifier in each one. Same for when I click one and see it in the top bar.

<img width="393" alt="Screen Shot 2021-11-19 at 1 33 13 PM" src="https://user-images.githubusercontent.com/198048/142694350-cf63f944-83fb-4853-9b8a-cbb8b422d6bd.png">

Is there more I'm supposed to provide when initiating the remote logger to get this info?

**Comment by kean** [comment]
I added more details in the new Pulse app for macOS. The first [pre-release](https://github.com/kean/Pulse/releases/tag/3.6.0-alpha.1) version if available.

<img width="618" alt="Screenshot 2023-03-26 at 7 49 17 PM" src="https://user-images.githubusercontent.com/1567433/227812570-0ed0bd11-7904-426f-a66b-9db7bd623b43.png">

**Comment by kean** [comment]
And one more update in the upcoming version:

![Screenshot 2023-04-08 at 12 18 48 PM](https://user-images.githubusercontent.com/1567433/230731928-a048ff11-d26f-41e6-ae94-772502270e65.png)
