### ISSUE TITLE
PulsePro Crash - 1.4.0

### ISSUE THREAD

**Issue by sgruby** [kean/PulsePro#17]
App crashed while streaming logs from a local simulator. This happens periodically.

Please let me know if you need more info.

[crash.txt](https://github.com/kean/PulsePro/files/7650619/crash.txt)

**Comment by kean** [comment]
Hi, @sgruby. Are you still experiencing this issue? The logs isn't symbolicated, so it's hard to tell why it occurs.

**Comment by kean** [comment]
May be related https://github.com/kean/PulsePro/issues/22

**Comment by sgruby** [comment]
I haven't been using PulsePro lately (working on a different project), so I really don't know. I'd go ahead and close it if there aren't other reports and you can't reproduce it.

**Comment by kean** [comment]
I'm going to close it because it's been largely rewritten for 2.0, so I hope it no longer crashes.
