### ISSUE TITLE
Feature Request - Remember Tab in Network Log Line

### ISSUE THREAD

**Issue by sgruby** [kean/PulsePro#18]
Sometimes I select Summary tab for a network request (Response, Request, Headers, Summary, Metrics, cURL) and then flip to a different entry to compare the requests. The tab changes so I have to select Summary again to compare.

It would be nice if it kept the selected tab. I guess this applies to the non-Pro version as well.

**Comment by kean** [comment]
Implemented in [Pulse Pro 2.0](https://github.com/kean/PulsePro/pull/26)
