### ISSUE TITLE
Show Metadata

### ISSUE THREAD

**Issue by Sherlouk** [kean/PulsePro#23]
Mirroring https://github.com/kean/Pulse/pull/81, it would be awesome if Pulse Pro could see all of the metadata attached to a log message! ❤️ 

I know the data exists already (you can filter on it) but would be nice to be able to see it rendered, perhaps in some form of table or collapsible tree view.

**Comment by kean** [comment]
Done and will be released in Pulse 2.0. The preview is available here  https://github.com/kean/PulsePro/pull/26

![Screen Shot 2022-07-20 at 7 13 17 PM](https://user-images.githubusercontent.com/1567433/180098073-7a4b7d0b-633e-4371-a5d2-8e0212e1b721.png)
