### ISSUE TITLE
Remove RemoteLogger logs

### ISSUE THREAD

**Issue by hugovanderlei** [kean/PulsePro#25]
Is there a way to remove or silence  the RemoveLogger logs on Xcode? It is polluting the console outputs

![Captura de Tela 2022-07-12 às 11 29 28](https://user-images.githubusercontent.com/184836/178515146-a0dc3de1-741c-4511-9a5a-9d6395e7248d.png)

**Comment by kean** [comment]
I'm removing all logs in [Pulse 2.0](https://github.com/kean/Pulse/pull/87). Releasing soon, but you can install from the branch for now if you'd like.
