### ISSUE TITLE
Pulse Pro 2.0 (Beta 1) - Missing package product PulseCore

### ISSUE THREAD

**Issue by hugovanderlei** [kean/PulsePro#28]
I cannot build the project, it's missing package PulseCore, i tried to add manually but it didn't work. Can you add the binary to the assets?
![Captura de Tela 2022-08-08 às 10 43 40](https://user-images.githubusercontent.com/184836/183432769-e0f160d0-faaa-48a4-bf37-4b69776462ac.png)
![Captura de Tela 2022-08-08 às 10 43 34](https://user-images.githubusercontent.com/184836/183432775-d8b486a6-e60f-48f0-b858-96146a6c6261.png)

**Comment by kean** [comment]
Hi, @hugovanderlei. You need to install the submodules before building the app.

It's set up this way because I'm using internal APIs from PulseUI and haven't yet found a better way.
