### ISSUE TITLE
Crash on Pulse Pro 2.0 (Beta 2) 

### ISSUE THREAD

**Issue by hugovanderlei** [kean/PulsePro#29]
I'm running Pulse 2.0.1 and Pulse Pro 2.0. (beta 2). When receiving remote logs, the app crashes.

bellow is the crash report:

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Pulse Pro [82307]
Path:                  /Applications/Pulse Pro 2.app/Contents/MacOS/Pulse Pro
Identifier:            com.github.kean.pulse-pro
Version:               2.0.0-beta.2 (1)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-08-16 15:26:20.8717 -0300
OS Version:            macOS 12.5 (21G72)
Report Version:        12
Anonymous UUID:        3E030ECF-D3F3-1725-1492-531647322FA1

Sleep/Wake UUID:       7626C2EB-C547-4F42-B2A1-C2D5F31CC998

Time Awake Since Boot: 60000 seconds
Time Since Wake:       24742 seconds

System Integrity Protection: enabled

Crashed Thread:        4  Dispatch queue: NSManagedObjectContext 0x6000032881a0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x00000001022a776c
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [82307]

Thread 0::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x1929f68b0 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x1929f6d20 mach_msg + 76
2   CoreFoundation                	       0x192b012c0 __CFRunLoopServiceMachPort + 372
3   CoreFoundation                	       0x192aff770 __CFRunLoopRun + 1180
4   CoreFoundation                	       0x192afeb34 CFRunLoopRunSpecific + 600
5   HIToolbox                     	       0x19b73e338 RunCurrentEventLoopInMode + 292
6   HIToolbox                     	       0x19b73e0b4 ReceiveNextEventCommon + 564
7   HIToolbox                     	       0x19b73de68 _BlockUntilNextEventMatchingListInModeWithFilter + 72
8   AppKit                        	       0x19566651c _DPSNextEvent + 860
9   AppKit                        	       0x195664e14 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1328
10  AppKit                        	       0x195656fe0 -[NSApplication run] + 596
11  AppKit                        	       0x1956286fc NSApplicationMain + 1132
12  SwiftUI                       	       0x1b807de98 specialized runApp(_:) + 148
13  SwiftUI                       	       0x1b8c0c588 runApp<A>(_:) + 260
14  SwiftUI                       	       0x1b868226c static App.main() + 128
15  Pulse Pro                     	       0x1021123a4 0x102108000 + 41892
16  dyld                          	       0x10257908c start + 520

Thread 1:
0   libsystem_pthread.dylib       	       0x192a2f078 start_wqthread + 0

Thread 2:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x1929f68b0 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x1929f6d20 mach_msg + 76
2   CoreFoundation                	       0x192b012c0 __CFRunLoopServiceMachPort + 372
3   CoreFoundation                	       0x192aff770 __CFRunLoopRun + 1180
4   CoreFoundation                	       0x192afeb34 CFRunLoopRunSpecific + 600
5   AppKit                        	       0x1957d3100 _NSEventThread + 196
6   libsystem_pthread.dylib       	       0x192a3426c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x192a2f08c thread_start + 8

Thread 3:
0   libsystem_pthread.dylib       	       0x192a2f078 start_wqthread + 0

Thread 4 Crashed::  Dispatch queue: NSManagedObjectContext 0x6000032881a0
0   Pulse Pro                     	       0x1022a776c 0x102108000 + 1701740
1   Pulse Pro                     	       0x1022a718c 0x102108000 + 1700236
2   Pulse Pro                     	       0x1022a5118 0x102108000 + 1691928
3   Pulse Pro                     	       0x1022a2dd4 0x102108000 + 1682900
4   Pulse Pro                     	       0x1022a8378 0x102108000 + 1704824
5   Pulse Pro                     	       0x1022e015c 0x102108000 + 1933660
6   CoreData                      	       0x198b6beb4 developerSubmittedBlockToNSManagedObjectContextPerform + 156
7   libdispatch.dylib             	       0x1928701b4 _dispatch_client_callout + 20
8   libdispatch.dylib             	       0x1928778a8 _dispatch_lane_serial_drain + 668
9   libdispatch.dylib             	       0x192878404 _dispatch_lane_invoke + 392
10  libdispatch.dylib             	       0x192882c98 _dispatch_workloop_worker_thread + 648
11  libsystem_pthread.dylib       	       0x192a30360 _pthread_wqthread + 288
12  libsystem_pthread.dylib       	       0x192a2f080 start_wqthread + 8

Thread 4 crashed with ARM Thread State (64-bit):
    x0: 0x000000016de08820   x1: 0x00000001dcd6f852   x2: 0x00000001ec23ea68   x3: 0x00000001ec23ea68
    x4: 0x0000000000000000   x5: 0x0000000000000001   x6: 0x0000000000000001   x7: 0x0000000000000000
    x8: 0x83ebd8956a3f0073   x9: 0x83ebd8956a3f0073  x10: 0x000000040000078c  x11: 0x000000000000007f
   x12: 0x0000000000000052  x13: 0x000000012a843d10  x14: 0x000000003e000000  x15: 0x00000001eb48d450
   x16: 0x00000001eb48d450  x17: 0x531a800192a9ed4c  x18: 0x0000000000000000  x19: 0x000000016de09a68
   x20: 0x00000000ffffc02f  x21: 0x000000016de08820  x22: 0x00000001022c100c  x23: 0x0000600002a334d0
   x24: 0x000000010238bfc8  x25: 0x0000000000000000  x26: 0x000000016de08a20  x27: 0x000000016de08a10
   x28: 0x000000016de08670   fp: 0x000000016de08b70   lr: 0x00000001022a718c
    sp: 0x000000016de084c0   pc: 0x00000001022a776c cpsr: 0x60001000
   far: 0x00000001dd258f59  esr: 0xf2000001 (Breakpoint) brk 1

Binary Images:
       0x1929f5000 -        0x192a2cfff libsystem_kernel.dylib (*) <67f22904-88ed-3847-bbf0-5c4c599fd79e> /usr/lib/system/libsystem_kernel.dylib
       0x192a7c000 -        0x192fc2fff com.apple.CoreFoundation (6.9) <1643f3d9-7049-37e4-b844-c0c0a42bde3b> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x19b70c000 -        0x19ba3ffff com.apple.HIToolbox (2.1.1) <7112f6f2-a77e-39db-83c8-f627b8a49df8> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
       0x195625000 -        0x1964ddfff com.apple.AppKit (6.9) <07bc3607-552a-3eb9-a941-4911c589dbc5> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x1b7fe9000 -        0x1b9038fff com.apple.SwiftUI (3.5.2) <a7231267-3c5e-3a0e-8b80-95100076e8fd> /System/Library/Frameworks/SwiftUI.framework/Versions/A/SwiftUI
       0x102108000 -        0x102357fff com.github.kean.pulse-pro (2.0.0-beta.2) <51f60b5e-f87e-38f5-a315-886baae0c6db> /Applications/Pulse Pro 2.app/Contents/MacOS/Pulse Pro
       0x102574000 -        0x1025d3fff dyld (*) <75627683-a780-32ad-ae34-cf86dd23a26b> /usr/lib/dyld
       0x192a2d000 -        0x192a39fff libsystem_pthread.dylib (*) <f32ff902-ba43-30b0-ad43-a2a8a9ff69fe> /usr/lib/system/libsystem_pthread.dylib
       0x198b3c000 -        0x198f11fff com.apple.CoreData (120) <11c6f60b-9498-3300-a89f-5c5990f9da44> /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
       0x19286c000 -        0x1928b2fff libdispatch.dylib (*) <035d23d9-4cb5-3759-9059-1f7878f89fee> /usr/lib/system/libdispatch.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)
Writable regions: Total=1.7G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.7G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               384K        3 
Activity Tracing                   256K        1 
CG backing stores                 2944K        8 
CG image                          1008K       25 
ColorSync                          592K       26 
CoreAnimation                     30.3M       57 
CoreData Object IDs               4112K        2 
CoreGraphics                        48K        3 
CoreUI image data                 1216K       12 
Foundation                          16K        1 
Kernel Alloc Once                   32K        1 
MALLOC                           333.4M       56 
MALLOC guard page                  192K       10 
MALLOC_MEDIUM (reserved)         960.0M        8         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
SQLite page cache                  512K        8 
STACK GUARD                       56.1M        5 
Stack                             10.1M        5 
VM_ALLOCATE                       1376K       23 
__AUTH                            2476K      263 
__AUTH_CONST                      18.9M      453 
__CTF                               756        1 
__DATA                            12.4M      446 
__DATA_CONST                      16.0M      461 
__DATA_DIRTY                      1566K      172 
__FONT_DATA                          4K        1 
__LINKEDIT                       578.1M        7 
__OBJC_CONST                      2709K      221 
__OBJC_RO                         83.0M        1 
__OBJC_RW                         3168K        1 
__TEXT                           456.4M      478 
__UNICODE                          592K        1 
dyld private memory               1024K        1 
mapped file                      183.5M       29 
shared memory                      896K       16 
===========                     =======  ======= 
TOTAL                              3.1G     2807 
TOTAL, minus reserved VM space     1.8G     2807 

-----------
Full Report
-----------

{"app_name":"Pulse Pro","timestamp":"2022-08-16 15:26:23.00 -0300","app_version":"2.0.0-beta.2","slice_uuid":"51f60b5e-f87e-38f5-a315-886baae0c6db","build_version":"1","platform":1,"bundleID":"com.github.kean.pulse-pro","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.5 (21G72)","incident_id":"18578951-0D21-4903-94D0-D785F3E750F6","name":"Pulse Pro"}
{
  "uptime" : 60000,
  "procLaunch" : "2022-08-16 15:25:29.6724 -0300",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro17,1",
  "procStartAbsTime" : 1457933315769,
  "coalitionID" : 7541,
  "osVersion" : {
    "train" : "macOS 12.5",
    "build" : "21G72",
    "releaseType" : "User"
  },
  "captureTime" : "2022-08-16 15:26:20.8717 -0300",
  "incident" : "18578951-0D21-4903-94D0-D785F3E750F6",
  "bug_type" : "309",
  "pid" : 82307,
  "procExitAbsTime" : 1459154803116,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "Pulse Pro",
  "procPath" : "\/Applications\/Pulse Pro 2.app\/Contents\/MacOS\/Pulse Pro",
  "bundleInfo" : {"CFBundleShortVersionString":"2.0.0-beta.2","CFBundleVersion":"1","CFBundleIdentifier":"com.github.kean.pulse-pro"},
  "storeInfo" : {"deviceIdentifierForVendor":"FFBC5351-4908-5889-A160-B611BEF0AED6","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.github.kean.pulse-pro",
  "crashReporterKey" : "3E030ECF-D3F3-1725-1492-531647322FA1",
  "wakeTime" : 24742,
  "sleepWakeUUID" : "7626C2EB-C547-4F42-B2A1-C2D5F31CC998",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x00000001022a776c","rawCodes":[1,4331304812],"type":"EXC_BREAKPOINT","signal":"SIGTRAP"},
  "termination" : {"flags":0,"code":5,"namespace":"SIGNAL","indicator":"Trace\/BPT trap: 5","byProc":"exc handler","byPid":82307},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 4,
  "threads" : [{"id":966796,"queue":"com.apple.main-thread","frames":[{"imageOffset":6320,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":7456,"symbol":"mach_msg","symbolLocation":76,"imageIndex":0},{"imageOffset":545472,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":372,"imageIndex":1},{"imageOffset":538480,"symbol":"__CFRunLoopRun","symbolLocation":1180,"imageIndex":1},{"imageOffset":535348,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":1},{"imageOffset":205624,"symbol":"RunCurrentEventLoopInMode","symbolLocation":292,"imageIndex":2},{"imageOffset":204980,"symbol":"ReceiveNextEventCommon","symbolLocation":564,"imageIndex":2},{"imageOffset":204392,"symbol":"_BlockUntilNextEventMatchingListInModeWithFilter","symbolLocation":72,"imageIndex":2},{"imageOffset":267548,"symbol":"_DPSNextEvent","symbolLocation":860,"imageIndex":3},{"imageOffset":261652,"symbol":"-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]","symbolLocation":1328,"imageIndex":3},{"imageOffset":204768,"symbol":"-[NSApplication run]","symbolLocation":596,"imageIndex":3},{"imageOffset":14076,"symbol":"NSApplicationMain","symbolLocation":1132,"imageIndex":3},{"imageOffset":609944,"symbol":"specialized runApp(_:)","symbolLocation":148,"imageIndex":4},{"imageOffset":12727688,"symbol":"runApp<A>(_:)","symbolLocation":260,"imageIndex":4},{"imageOffset":6918764,"symbol":"static App.main()","symbolLocation":128,"imageIndex":4},{"imageOffset":41892,"imageIndex":5},{"imageOffset":20620,"symbol":"start","symbolLocation":520,"imageIndex":6}]},{"id":966861,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":966898,"name":"com.apple.NSEventThread","frames":[{"imageOffset":6320,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":7456,"symbol":"mach_msg","symbolLocation":76,"imageIndex":0},{"imageOffset":545472,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":372,"imageIndex":1},{"imageOffset":538480,"symbol":"__CFRunLoopRun","symbolLocation":1180,"imageIndex":1},{"imageOffset":535348,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":1},{"imageOffset":1761536,"symbol":"_NSEventThread","symbolLocation":196,"imageIndex":3},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":967121,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"triggered":true,"id":967304,"threadState":{"x":[{"value":6138398752},{"value":8000043090,"objc-selector":"release"},{"value":8256744040,"symbolLocation":0,"symbol":"type metadata for Date"},{"value":8256744040,"symbolLocation":0,"symbol":"type metadata for Date"},{"value":0},{"value":1},{"value":1},{"value":0},{"value":9505929574739804275},{"value":9505929574739804275},{"value":17179871116},{"value":127},{"value":82},{"value":5008276752},{"value":1040187392},{"value":8242386000,"symbolLocation":0,"symbol":"OBJC_CLASS_$___NSCFString"},{"value":8242386000,"symbolLocation":0,"symbol":"OBJC_CLASS_$___NSCFString"},{"value":5988239398786428236,"symbolLocation":5988239392030851072,"symbol":"-[__NSCFString release]"},{"value":0},{"value":6138403432},{"value":4294950959},{"value":6138398752},{"value":4331409420},{"value":105553160516816},{"value":4332240840},{"value":0},{"value":6138399264},{"value":6138399248},{"value":6138398320}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4331303308},"cpsr":{"value":1610616832},"fp":{"value":6138399600},"sp":{"value":6138397888},"esr":{"value":4060086273,"description":"(Breakpoint) brk 1"},"pc":{"value":4331304812,"matchesCrashFrame":1},"far":{"value":8005193561}},"queue":"NSManagedObjectContext 0x6000032881a0","frames":[{"imageOffset":1701740,"imageIndex":5},{"imageOffset":1700236,"imageIndex":5},{"imageOffset":1691928,"imageIndex":5},{"imageOffset":1682900,"imageIndex":5},{"imageOffset":1704824,"imageIndex":5},{"imageOffset":1933660,"imageIndex":5},{"imageOffset":196276,"symbol":"developerSubmittedBlockToNSManagedObjectContextPerform","symbolLocation":156,"imageIndex":8},{"imageOffset":16820,"symbol":"_dispatch_client_callout","symbolLocation":20,"imageIndex":9},{"imageOffset":47272,"symbol":"_dispatch_lane_serial_drain","symbolLocation":668,"imageIndex":9},{"imageOffset":50180,"symbol":"_dispatch_lane_invoke","symbolLocation":392,"imageIndex":9},{"imageOffset":93336,"symbol":"_dispatch_workloop_worker_thread","symbolLocation":648,"imageIndex":9},{"imageOffset":13152,"symbol":"_pthread_wqthread","symbolLocation":288,"imageIndex":7},{"imageOffset":8320,"symbol":"start_wqthread","symbolLocation":8,"imageIndex":7}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6754881536,
    "size" : 229376,
    "uuid" : "67f22904-88ed-3847-bbf0-5c4c599fd79e",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6755434496,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5533696,
    "uuid" : "1643f3d9-7049-37e4-b844-c0c0a42bde3b",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1866"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6902824960,
    "CFBundleShortVersionString" : "2.1.1",
    "CFBundleIdentifier" : "com.apple.HIToolbox",
    "size" : 3358720,
    "uuid" : "7112f6f2-a77e-39db-83c8-f627b8a49df8",
    "path" : "\/System\/Library\/Frameworks\/Carbon.framework\/Versions\/A\/Frameworks\/HIToolbox.framework\/Versions\/A\/HIToolbox",
    "name" : "HIToolbox"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6801215488,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15437824,
    "uuid" : "07bc3607-552a-3eb9-a941-4911c589dbc5",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2113.60.148"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7381880832,
    "CFBundleShortVersionString" : "3.5.2",
    "CFBundleIdentifier" : "com.apple.SwiftUI",
    "size" : 17104896,
    "uuid" : "a7231267-3c5e-3a0e-8b80-95100076e8fd",
    "path" : "\/System\/Library\/Frameworks\/SwiftUI.framework\/Versions\/A\/SwiftUI",
    "name" : "SwiftUI",
    "CFBundleVersion" : "3.5.2"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4329603072,
    "CFBundleShortVersionString" : "2.0.0-beta.2",
    "CFBundleIdentifier" : "com.github.kean.pulse-pro",
    "size" : 2424832,
    "uuid" : "51f60b5e-f87e-38f5-a315-886baae0c6db",
    "path" : "\/Applications\/Pulse Pro 2.app\/Contents\/MacOS\/Pulse Pro",
    "name" : "Pulse Pro",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4334239744,
    "size" : 393216,
    "uuid" : "75627683-a780-32ad-ae34-cf86dd23a26b",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6755110912,
    "size" : 53248,
    "uuid" : "f32ff902-ba43-30b0-ad43-a2a8a9ff69fe",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6856884224,
    "CFBundleShortVersionString" : "120",
    "CFBundleIdentifier" : "com.apple.CoreData",
    "size" : 4022272,
    "uuid" : "11c6f60b-9498-3300-a89f-5c5990f9da44",
    "path" : "\/System\/Library\/Frameworks\/CoreData.framework\/Versions\/A\/CoreData",
    "name" : "CoreData",
    "CFBundleVersion" : "1152.5"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6753271808,
    "size" : 290816,
    "uuid" : "035d23d9-4cb5-3759-9059-1f7878f89fee",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  }
],
  "sharedCache" : {
  "base" : 6751813632,
  "size" : 3144695808,
  "uuid" : "ffede77c-d90b-366b-96f2-665c2f50ee59"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)\nWritable regions: Total=1.7G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.7G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               384K        3 \nActivity Tracing                   256K        1 \nCG backing stores                 2944K        8 \nCG image                          1008K       25 \nColorSync                          592K       26 \nCoreAnimation                     30.3M       57 \nCoreData Object IDs               4112K        2 \nCoreGraphics                        48K        3 \nCoreUI image data                 1216K       12 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           333.4M       56 \nMALLOC guard page                  192K       10 \nMALLOC_MEDIUM (reserved)         960.0M        8         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSQLite page cache                  512K        8 \nSTACK GUARD                       56.1M        5 \nStack                             10.1M        5 \nVM_ALLOCATE                       1376K       23 \n__AUTH                            2476K      263 \n__AUTH_CONST                      18.9M      453 \n__CTF                               756        1 \n__DATA                            12.4M      446 \n__DATA_CONST                      16.0M      461 \n__DATA_DIRTY                      1566K      172 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       578.1M        7 \n__OBJC_CONST                      2709K      221 \n__OBJC_RO                         83.0M        1 \n__OBJC_RW                         3168K        1 \n__TEXT                           456.4M      478 \n__UNICODE                          592K        1 \ndyld private memory               1024K        1 \nmapped file                      183.5M       29 \nshared memory                      896K       16 \n===========                     =======  ======= \nTOTAL                              3.1G     2807 \nTOTAL, minus reserved VM space     1.8G     2807 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "NSManagedObjectContext 0x6000032881a0"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "61301e3a61217b3110231469",
      "factorPackIds" : {
        "SIRI_FIND_MY_CONFIGURATION_FILES" : "6216ae152a40e71046e16225"
      },
      "deploymentId" : 240000016
    },
    {
      "rolloutId" : "60186475825c62000ccf5450",
      "factorPackIds" : {

      },
      "deploymentId" : 240000025
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro17,1, BootROM 7459.141.1, proc 8:4:4 processors, 8 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Display: DELL U2419H, 1920 x 1080 (1080p FHD - Full High Definition), MirrorOff, Online
Memory Module: LPDDR4
AirPort: Wi-Fi, wl0: Mar 23 2022 19:57:59 version 18.60.27.0.7.8.129 FWID 01-570be953
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB3.0 Hub
USB Device: USB 10/100/1000 LAN
USB Device: USB3.0 Card Reader
USB Device: USB2.0 Hub
USB Device: iPhone
USB Device: USB 2.0 Hub
USB Device: BillBoard Device
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

**Comment by kean** [comment]
Right, it needs to be updated to the latest Pulse version.

**Comment by kean** [comment]
Please try now https://github.com/kean/PulsePro/releases/tag/2.0.0-beta.3.
I'm assuming it's the same issue. It doesn't crash now.
