### ISSUE TITLE
Pulse Pro 2.0 - Would be great if there was a way to see store info like you can on the iOS version.

### ISSUE THREAD

**Issue by OscarGorog** [kean/PulsePro#30]
On the iOS version of the Pulse viewer, you can go to the settings tab and click on the store details cell to see those details.

It would be great if you could also see this information on the Mac app.

Thanks! 😀

**Comment by kean** [comment]
The store details are available in the [pre-release version](https://github.com/kean/Pulse/releases/tag/3.6.0-alpha.1) of the new macOS app designed to be a Pulse Pro replacement. It shares most of the code with the iOS version and I strive for a complete feature parity this time.

<img width="706" alt="Screenshot 2023-03-26 at 7 50 37 PM" src="https://user-images.githubusercontent.com/1567433/227812635-664402ca-b347-4034-8cf0-049f610f54e9.png">
