### ISSUE TITLE
Right-clicking the left sidebar after first launch (empty state) crashes the app

### ISSUE THREAD

**Issue by DivineDominion** [kean/PulsePro#31]
A right-click in the sidebar crashes the app immediately. I marked the region in this screenshot:

![Screen Shot 2022-08-30 at 15 18 14](https://user-images.githubusercontent.com/59080/187447200-b46e9dbf-87e7-4095-a0eb-d5657b3f11db.png)

macOS 12.5.1 (21G83)

<details>
<summary>Crash log</summary>
<pre><code>
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Pulse Pro [93928]
Path:                  /Applications/Pulse Pro.app/Contents/MacOS/Pulse Pro
Identifier:            com.github.kean.pulse-pro
Version:               1.4.1 (1)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               502

Date/Time:             2022-08-30 15:16:32.3498 +0200
OS Version:            macOS 12.5.1 (21G83)
Report Version:        12
Anonymous UUID:        D7874865-BECB-E4FC-9DB9-D668B6DC3D61

Sleep/Wake UUID:       EEF82BF8-BA15-4C44-8A12-FD1E153725C5

Time Awake Since Boot: 480000 seconds
Time Since Wake:       5728 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x00000001022d1cbc
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [93928]

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   Pulse Pro                     	       0x1022d1cbc 0x102298000 + 236732
1   Pulse Pro                     	       0x1022d18c4 0x102298000 + 235716
2   Pulse Pro                     	       0x1022d1cf0 0x102298000 + 236784
3   AppKit                        	       0x1c24563e8 -[NSView _showMenuForEvent:] + 72
4   AppKit                        	       0x1c1f988a0 -[NSView rightMouseDown:] + 108
5   AppKit                        	       0x1c20cb194 -[NSControl _rightMouseUpOrDown:] + 472
6   AppKit                        	       0x1c1d3be88 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 5908
7   AppKit                        	       0x1c1d3a50c -[NSWindow(NSEventRouting) sendEvent:] + 348
8   AppKit                        	       0x1c1d394b4 -[NSApplication(NSEvent) sendEvent:] + 2780
9   AppKit                        	       0x1c1ff30f4 -[NSApplication _handleEvent:] + 76
10  AppKit                        	       0x1c1bbb008 -[NSApplication run] + 636
11  AppKit                        	       0x1c1b8c6fc NSApplicationMain + 1132
12  SwiftUI                       	       0x1e45e1e98 specialized runApp(_:) + 148
13  SwiftUI                       	       0x1e5170588 runApp<A>(_:) + 260
14  SwiftUI                       	       0x1e4be626c static App.main() + 128
15  Pulse Pro                     	       0x10229a648 0x102298000 + 9800
16  dyld                          	       0x10284d08c start + 520

Thread 1:
0   libsystem_pthread.dylib       	       0x1bef93078 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x1bef93078 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x1bef93078 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	       0x1bef93078 start_wqthread + 0

Thread 5:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x1bef5a8b0 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x1bef5ad20 mach_msg + 76
2   CoreFoundation                	       0x1bf0652c0 __CFRunLoopServiceMachPort + 372
3   CoreFoundation                	       0x1bf063770 __CFRunLoopRun + 1180
4   CoreFoundation                	       0x1bf062b34 CFRunLoopRunSpecific + 600
5   AppKit                        	       0x1c1d37100 _NSEventThread + 196
6   libsystem_pthread.dylib       	       0x1bef9826c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x1bef9308c thread_start + 8

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x00006000010acb40   x1: 0x00006000010acb40   x2: 0x00000001bee2833c   x3: 0x00006000010acb40
    x4: 0x00000001bee469b1   x5: 0x00000001bee469a5   x6: 0x00000002092d4a30   x7: 0x00000002092d4a30
    x8: 0x00006000034f93c0   x9: 0x0000000000000001  x10: 0x0000000000000001  x11: 0x00006000010acb50
   x12: 0x0000000000000000  x13: 0x0000000000000000  x14: 0x00000001bec6c000  x15: 0x000000027a374000
   x16: 0x00000001024bb5ba  x17: 0x00000001c1b94bac  x18: 0x0000000000000000  x19: 0x00006000014b3b40
   x20: 0x0000000147078400  x21: 0x00000001024bb688  x22: 0xffffffffffffffff  x23: 0x00006000010acb40
   x24: 0x00000002092d8000  x25: 0x0000000000000000  x26: 0x000000002bd80025  x27: 0x0000000000000000
   x28: 0x00000000000000fc   fp: 0x000000016db66fc0   lr: 0xf8640001022d18c4
    sp: 0x000000016db66f30   pc: 0x00000001022d1cbc cpsr: 0xa0001000
   far: 0x00000001032b8000  esr: 0xf2000001 (Breakpoint) brk 1

Binary Images:
       0x102298000 -        0x102497fff com.github.kean.pulse-pro (1.4.1) <a76212a2-28a4-3434-b97c-9bd9f50c3888> /Applications/Pulse Pro.app/Contents/MacOS/Pulse Pro
       0x1c1b89000 -        0x1c2a41fff com.apple.AppKit (6.9) <07bc3607-552a-3eb9-a941-4911c589dbc5> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x1e454d000 -        0x1e559cfff com.apple.SwiftUI (3.5.2) <a7231267-3c5e-3a0e-8b80-95100076e8fd> /System/Library/Frameworks/SwiftUI.framework/Versions/A/SwiftUI
       0x102848000 -        0x1028a7fff dyld (*) <75627683-a780-32ad-ae34-cf86dd23a26b> /usr/lib/dyld
       0x1bef91000 -        0x1bef9dfff libsystem_pthread.dylib (*) <f32ff902-ba43-30b0-ad43-a2a8a9ff69fe> /usr/lib/system/libsystem_pthread.dylib
       0x1bef59000 -        0x1bef90fff libsystem_kernel.dylib (*) <d5cdde7e-7037-3a70-9ce4-9e3847da6ce0> /usr/lib/system/libsystem_kernel.dylib
       0x1befe0000 -        0x1bf526fff com.apple.CoreFoundation (6.9) <1643f3d9-7049-37e4-b844-c0c0a42bde3b> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 1084
    thread_create: 5
    thread_set_state: 17186

VM Region Summary:
ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)
Writable regions: Total=1.7G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.7G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               128K        1 
Activity Tracing                   256K        1 
CG backing stores                 4864K        8 
CG image                           128K        5 
ColorSync                          592K       26 
CoreAnimation                      592K       31 
CoreGraphics                        32K        2 
CoreUI image data                  496K        9 
Foundation                          16K        1 
Kernel Alloc Once                   32K        1 
MALLOC                           305.3M       53 
MALLOC guard page                  192K       10 
MALLOC_MEDIUM (reserved)           1.1G        9         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.1M        6 
Stack                             10.6M        6 
VM_ALLOCATE                       1200K       12 
__AUTH                            2438K      254 
__AUTH_CONST                      18.7M      442 
__CTF                               756        1 
__DATA                            12.2M      430 
__DATA_CONST                      15.6M      447 
__DATA_DIRTY                      1554K      168 
__FONT_DATA                          4K        1 
__LINKEDIT                       577.8M        4 
__OBJC_CONST                      2623K      210 
__OBJC_RO                         83.0M        1 
__OBJC_RW                         3168K        1 
__TEXT                           450.8M      464 
__UNICODE                          592K        1 
dyld private memory               1024K        1 
mapped file                      179.8M       23 
shared memory                     1584K       21 
===========                     =======  ======= 
TOTAL                              3.1G     2651 
TOTAL, minus reserved VM space     1.7G     2651 

-----------
Full Report
-----------

{"app_name":"Pulse Pro","timestamp":"2022-08-30 15:16:32.00 +0200","app_version":"1.4.1","slice_uuid":"a76212a2-28a4-3434-b97c-9bd9f50c3888","build_version":"1","platform":1,"bundleID":"com.github.kean.pulse-pro","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.5.1 (21G83)","incident_id":"1B313515-BEF8-4DF7-9D88-FF6C7C1FF639","name":"Pulse Pro"}
{
  "uptime" : 480000,
  "procLaunch" : "2022-08-30 15:16:31.2618 +0200",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 502,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,4",
  "procStartAbsTime" : 11635225322801,
  "coalitionID" : 231853,
  "osVersion" : {
    "train" : "macOS 12.5.1",
    "build" : "21G83",
    "releaseType" : "User"
  },
  "captureTime" : "2022-08-30 15:16:32.3498 +0200",
  "incident" : "1B313515-BEF8-4DF7-9D88-FF6C7C1FF639",
  "bug_type" : "309",
  "pid" : 93928,
  "procExitAbsTime" : 11635250735743,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "Pulse Pro",
  "procPath" : "\/Applications\/Pulse Pro.app\/Contents\/MacOS\/Pulse Pro",
  "bundleInfo" : {"CFBundleShortVersionString":"1.4.1","CFBundleVersion":"1","CFBundleIdentifier":"com.github.kean.pulse-pro"},
  "storeInfo" : {"deviceIdentifierForVendor":"E387336C-08B0-5D5E-B0DC-DB138B65AD26","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.github.kean.pulse-pro",
  "crashReporterKey" : "D7874865-BECB-E4FC-9DB9-D668B6DC3D61",
  "wakeTime" : 5728,
  "sleepWakeUUID" : "EEF82BF8-BA15-4C44-8A12-FD1E153725C5",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x00000001022d1cbc","rawCodes":[1,4331478204],"type":"EXC_BREAKPOINT","signal":"SIGTRAP"},
  "termination" : {"flags":0,"code":5,"namespace":"SIGNAL","indicator":"Trace\/BPT trap: 5","byProc":"exc handler","byPid":93928},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":5,"thread_set_state":17186,"task_for_pid":1084},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":7325039,"threadState":{"x":[{"value":105553133751104},{"value":105553133751104},{"value":7497483068,"symbolLocation":0,"symbol":"-[NSObject retainWeakReference]"},{"value":105553133751104},{"value":7497607601,"symbolLocation":321,"symbol":"_OBJC_$_INSTANCE_METHODS_NSObject"},{"value":7497607589,"symbolLocation":309,"symbol":"_OBJC_$_INSTANCE_METHODS_NSObject"},{"value":8743897648,"objc-selector":"init"},{"value":8743897648,"objc-selector":"init"},{"value":105553171813312},{"value":1},{"value":1},{"value":105553133751120},{"value":0},{"value":0},{"value":7495663616},{"value":10640375808},{"value":4333483450},{"value":7545113516,"symbolLocation":0,"symbol":"-[NSResponder _tryRetain]"},{"value":0},{"value":105553137974080},{"value":5486642176},{"value":4333483656},{"value":18446744073709551615},{"value":105553133751104},{"value":8743911424,"objc-selector":"PasteboardAvailable:"},{"value":0},{"value":735576101},{"value":0},{"value":252}],"flavor":"ARM_THREAD_STATE64","lr":{"value":17898430823408670916},"cpsr":{"value":2684358656},"fp":{"value":6135640000},"sp":{"value":6135639856},"esr":{"value":4060086273,"description":"(Breakpoint) brk 1"},"pc":{"value":4331478204,"matchesCrashFrame":1},"far":{"value":4348149760}},"queue":"com.apple.main-thread","frames":[{"imageOffset":236732,"imageIndex":0},{"imageOffset":235716,"imageIndex":0},{"imageOffset":236784,"imageIndex":0},{"imageOffset":9229288,"symbol":"-[NSView _showMenuForEvent:]","symbolLocation":72,"imageIndex":1},{"imageOffset":4257952,"symbol":"-[NSView rightMouseDown:]","symbolLocation":108,"imageIndex":1},{"imageOffset":5513620,"symbol":"-[NSControl _rightMouseUpOrDown:]","symbolLocation":472,"imageIndex":1},{"imageOffset":1781384,"symbol":"-[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:]","symbolLocation":5908,"imageIndex":1},{"imageOffset":1774860,"symbol":"-[NSWindow(NSEventRouting) sendEvent:]","symbolLocation":348,"imageIndex":1},{"imageOffset":1770676,"symbol":"-[NSApplication(NSEvent) sendEvent:]","symbolLocation":2780,"imageIndex":1},{"imageOffset":4628724,"symbol":"-[NSApplication _handleEvent:]","symbolLocation":76,"imageIndex":1},{"imageOffset":204808,"symbol":"-[NSApplication run]","symbolLocation":636,"imageIndex":1},{"imageOffset":14076,"symbol":"NSApplicationMain","symbolLocation":1132,"imageIndex":1},{"imageOffset":609944,"symbol":"specialized runApp(_:)","symbolLocation":148,"imageIndex":2},{"imageOffset":12727688,"symbol":"runApp<A>(_:)","symbolLocation":260,"imageIndex":2},{"imageOffset":6918764,"symbol":"static App.main()","symbolLocation":128,"imageIndex":2},{"imageOffset":9800,"imageIndex":0},{"imageOffset":20620,"symbol":"start","symbolLocation":520,"imageIndex":3}]},{"id":7325060,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":4}]},{"id":7325061,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":4}]},{"id":7325068,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":4}]},{"id":7325080,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":4}]},{"id":7325112,"name":"com.apple.NSEventThread","frames":[{"imageOffset":6320,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":5},{"imageOffset":7456,"symbol":"mach_msg","symbolLocation":76,"imageIndex":5},{"imageOffset":545472,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":372,"imageIndex":6},{"imageOffset":538480,"symbol":"__CFRunLoopRun","symbolLocation":1180,"imageIndex":6},{"imageOffset":535348,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":6},{"imageOffset":1761536,"symbol":"_NSEventThread","symbolLocation":196,"imageIndex":1},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":4},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":4}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4331241472,
    "CFBundleShortVersionString" : "1.4.1",
    "CFBundleIdentifier" : "com.github.kean.pulse-pro",
    "size" : 2097152,
    "uuid" : "a76212a2-28a4-3434-b97c-9bd9f50c3888",
    "path" : "\/Applications\/Pulse Pro.app\/Contents\/MacOS\/Pulse Pro",
    "name" : "Pulse Pro",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7545065472,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15437824,
    "uuid" : "07bc3607-552a-3eb9-a941-4911c589dbc5",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2113.60.148"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 8125730816,
    "CFBundleShortVersionString" : "3.5.2",
    "CFBundleIdentifier" : "com.apple.SwiftUI",
    "size" : 17104896,
    "uuid" : "a7231267-3c5e-3a0e-8b80-95100076e8fd",
    "path" : "\/System\/Library\/Frameworks\/SwiftUI.framework\/Versions\/A\/SwiftUI",
    "name" : "SwiftUI",
    "CFBundleVersion" : "3.5.2"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4337205248,
    "size" : 393216,
    "uuid" : "75627683-a780-32ad-ae34-cf86dd23a26b",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7498960896,
    "size" : 53248,
    "uuid" : "f32ff902-ba43-30b0-ad43-a2a8a9ff69fe",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7498731520,
    "size" : 229376,
    "uuid" : "d5cdde7e-7037-3a70-9ce4-9e3847da6ce0",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7499284480,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5533696,
    "uuid" : "1643f3d9-7049-37e4-b844-c0c0a42bde3b",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1866"
  }
],
  "sharedCache" : {
  "base" : 7495663616,
  "size" : 3144712192,
  "uuid" : "f8ab76fb-504c-32dd-a5db-15a1f2f028f8"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)\nWritable regions: Total=1.7G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.7G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               128K        1 \nActivity Tracing                   256K        1 \nCG backing stores                 4864K        8 \nCG image                           128K        5 \nColorSync                          592K       26 \nCoreAnimation                      592K       31 \nCoreGraphics                        32K        2 \nCoreUI image data                  496K        9 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           305.3M       53 \nMALLOC guard page                  192K       10 \nMALLOC_MEDIUM (reserved)           1.1G        9         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSTACK GUARD                       56.1M        6 \nStack                             10.6M        6 \nVM_ALLOCATE                       1200K       12 \n__AUTH                            2438K      254 \n__AUTH_CONST                      18.7M      442 \n__CTF                               756        1 \n__DATA                            12.2M      430 \n__DATA_CONST                      15.6M      447 \n__DATA_DIRTY                      1554K      168 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       577.8M        4 \n__OBJC_CONST                      2623K      210 \n__OBJC_RO                         83.0M        1 \n__OBJC_RW                         3168K        1 \n__TEXT                           450.8M      464 \n__UNICODE                          592K        1 \ndyld private memory               1024K        1 \nmapped file                      179.8M       23 \nshared memory                     1584K       21 \n===========                     =======  ======= \nTOTAL                              3.1G     2651 \nTOTAL, minus reserved VM space     1.7G     2651 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    },
    {
      "rolloutId" : "61301e3a61217b3110231469",
      "factorPackIds" : {
        "SIRI_FIND_MY_CONFIGURATION_FILES" : "6216ae152a40e71046e16225"
      },
      "deploymentId" : 240000016
    }
  ],
  "experiments" : [

  ]
}
}
</code></pre>
</details>

**Comment by kean** [comment]
Fixed in [2.0](https://github.com/kean/PulsePro/releases/tag/2.0.0)
