### ISSUE TITLE
Remote Logging with devices

### ISSUE THREAD

**Issue by sisomollov** [kean/PulsePro#32]
Hi, does anyone have problems connecting with the app using remote logging from devices? The simulator works but when I try to connect with iPhone or iPad doesn't show anything just endless 'Searching...'. 
I'm using Pulse Pro 2.0 beta3 and iOS 16

**Comment by hugovanderlei** [comment]
No problem here

**Comment by kean** [comment]
You need to be on the same local network. Other than that, there are no extra configuration steps for the device.

**Comment by sisomollov** [comment]
Yeah, I'm on the same network. Probable it's something in my setup

**Comment by sisomollov** [comment]
I have missed the .plist configuration in my app from step 4.1 in Getting Started. After that now everything is good

**Comment by kean** [comment]
Great. There is room for also improving the error handling. I should be able to figure out if .plist is configured properly at runtime.
