### ISSUE TITLE
Unable to open .pulse logs

### ISSUE THREAD

**Issue by jostster** [kean/PulsePro#33]
No matter what version of Pulse Pro I constantly get 
<img width="661" alt="image" src="https://user-images.githubusercontent.com/278510/191346349-3ea18236-8c2f-4b8c-a89d-34bc7e04c5a1.png">

**Comment by kean** [comment]
Which versions of `Pulse` and `Pulse Pro` are you using? If you are on Pulse 2.x, you need to use the latest Pulse Pro [beta](https://github.com/kean/PulsePro/releases/tag/2.0.0-beta.3). I'm planning to release a stable 2.x some time later – too busy with other things at the moment.

**Comment by jostster** [comment]
Our project is using SPM `master` for Pulse. With logs from our latest production build I've tried Pulse Pro 1.41 and the latest  2.0 beta, but get the above `Failed to open Pulse document` for both Pulse Pro versions.

**Comment by kean** [comment]
Try with [2.0](https://github.com/kean/PulsePro/releases/tag/2.0.0)
