### ISSUE TITLE
Bug: PulsePro doesn't seem to see all devices

### ISSUE THREAD

**Issue by MaximBazarov** [kean/PulsePro#34]
MacBook Air M1
macOS Ventura Version 13.0 Beta (22A5358e)

<img width="496" alt="Screenshot 2022-10-01 at 09 54 11" src="https://user-images.githubusercontent.com/11208417/193399368-c5f7b48d-6211-4686-93ba-9e0437d4e5b4.png">

I can see that device in Xcode and can run the app on it, but can't seem to be able to see it in Pulse Pro

**Comment by r-a-o** [comment]
Same problem, v2.0.0 mac app on Ventura (on M1 pro) does not list devices. @kean

**Comment by r-a-o** [comment]
However the older mac app version (1.4.1) works. @MaximBazarov

**Comment by kean** [comment]
Hey, please make sure to update to the latest versions of both Pulse and Pulse Pro. Both must be using version 2.0 or higher, preferably the latest release. There is also a new ["Getting Started"](https://kean-docs.github.io/pulse/documentation/pulse/gettingstarted) guide. Please follow the "4. Configure Remote Logging with Pulse Pro" section.

**Comment by jverkoey** [comment]
I'm able to get my iPhone to appear remotely in the app, but my paired watchOS app doesn't appear; the "Remote Logging" switch is enabled in the settings, but tapping my laptop from the watch just causes it to spin without the device appearing in PulsePro.
