### ISSUE TITLE
NetworkInspectorHeaderViewModel has been put into Trash

### ISSUE THREAD

**Issue by tualatrix** [kean/PulsePro#36]
Please see screenshot:

<img width="1118" alt="CleanShot 2023-02-03 at 16 54 15@2x" src="https://user-images.githubusercontent.com/35811/216555564-7d2dc957-c863-4419-ad3a-e7946d550f92.png">

**Comment by kean** [comment]
I removed a few couple of latest commits from the main branch, so it should be fixed now.

I initially made an attempt to upgrade Pulse Pro to PulseUI 3.x to get the latest updates, but realized that there are too many changes, and it would a perfect time to fully base Pulse Pro on PulseUI (and SwiftUI). Pulse Pro 3.x is coming some time later this month.
