### ISSUE TITLE
How to re-add Pulse dependency files?

### ISSUE THREAD

**Issue by leo150** [kean/PulsePro#38]
I made a fork of Pulse on top of the current master branch. A lot of files were moved/deleted/added so Compile Sources step has a lot of missing files. With CocoaPods this could be fixed with `pod install` as dependency files live in the separate targets. Is there any command/script to scramble all the required files together?

**Comment by kean** [comment]
The simplest option is to remove all the files from Xcode and add them back.

**Comment by kean** [comment]
I'm rewriting Pulse Pro using SwiftUI. The current version is written primarily using AppKit. The new one is using SwiftUI and uses a lot more of the code from PulseUI, so it's going to be much easier to work with.

I'm planning to release it later this month. The app target itself (Pulse Pro) will most likely move to the main repo.

**Comment by leo150** [comment]
Thanks, will wait for the update. I'm adding basic [charts](https://github.com/twitchalerts/Pulse-iOS/commits/master) support. Please take a look if you're interested. Might be hard for me to created a PR because of some compatibility commits like [this](https://github.com/kean/Pulse/commit/2e56d193800944ad43961898806722e109a5d276).

Here's how it looks:
<details>
  <summary>Screenshot</summary>
  
  
<img width="1101" alt="Screenshot 2023-02-03 at 11 56 38 AM" src="https://user-images.githubusercontent.com/3484524/216698132-aa8a85f3-1fc3-415f-9a3d-2c64ad90c0e1.png">

</details>

**Comment by kean** [comment]
That looks awesome. Do you have some examples of how you are planning to use it?

> Might be hard for me to created a PR because of some compatibility commits like [this](https://github.com/kean/Pulse/commit/2e56d193800944ad43961898806722e109a5d276).

Pulse 3.x requires iOS 14+.

**Comment by leo150** [comment]
Yes a basic example is to log the live stream bitrate and then present it as a chart. Our users then can send us a log file where this chart will help with debugging the performance issues. 

I've added all those `@available` because we cannot drop iOS 13 yet but we're fine to only provide logging to iOS to 14+ users.
