### ISSUE TITLE
Filtering by Level or Label doesn't work

### ISSUE THREAD

**Issue by leo150** [kean/PulsePro#45]
I logged some messages from iOS client. They appear fine in Pulse Pro version 4.0.0 (9). Whenever I try to filter them by "Label some-label-name" or "Level debug", I get 0 results.

<img width="486" alt="Screenshot 2023-08-04 at 5 03 23 PM" src="https://github.com/kean/PulsePro/assets/3484524/8a5b445c-fdb2-4d72-880b-7b21bedd5957">

**Comment by kean** [comment]
Hey, you need to select one of the suggestions, otherwise it performs a simple text-based search.

https://github.com/kean/PulsePro/assets/1567433/b6c26bbf-c4e9-4a0a-bd67-8ca49c92b190

**Comment by leo150** [comment]
Hey, thank you for the response and the video. I was hitting Enter key thinking that it selects the first option from the list. My text was exactly the same as the first option. But pressing Enter is just hiding options list. It works now, thanks! Would be great if Enter key works as well.
